[workspace]
resolver = "2"
members = [
    "crates/ink",
    "crates/metadata",
    "crates/allocator",
    "crates/ink",
    "crates/ink/macro",
    "crates/ink/ir",
    "crates/ink/codegen",
    "crates/ink/macro",
    "crates/prelude",
    "crates/primitives",
    "crates/engine",
    "crates/env",
    "crates/storage",
    "crates/storage/traits",
]
exclude = [
    "examples/",
]

[workspace.package]
version = "4.0.0-alpha.3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_env/"
homepage = "https://www.parity.io/"
description = "[ink!] Low-level interface for interacting with the smart contract Wasm executor."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[profile.release]
panic = "abort"
lto = true
