[package]
name = "ink_codegen"
documentation = "https://docs.rs/ink_codegen/"

version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[lib]
name = "ink_codegen"

[dependencies]
ink_primitives = { version = "4.0.0-alpha.3", path = "../../primitives" }
ir = { version = "4.0.0-alpha.3", package = "ink_ir", path = "../ir", default-features = false }
quote = "1"
syn = { version = "1.0", features = ["parsing", "full", "extra-traits"] }
proc-macro2 = "1.0"
derive_more = { version = "0.99", default-features = false, features = ["from"] }
itertools = "0.10"
either = { version = "1.5", default-features = false }
blake2 = "0.10"
heck = "0.4.0"
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "full"] }
impl-serde = "0.4.0"

[features]
default = ["std"]
std = [
    "itertools/use_std",
    "either/use_std",
    "ir/std"
]
