[package]
name = "ink_storage"
documentation = "https://docs.rs/ink_storage/"

version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[dependencies]
ink_env = { version = "4.0.0-alpha.3", path = "../env/", default-features = false }
ink_metadata = { version = "4.0.0-alpha.3", path = "../metadata/", default-features = false, features = ["derive"], optional = true }
ink_primitives = { version = "4.0.0-alpha.3", path = "../primitives/", default-features = false }
ink_storage_traits = { version = "4.0.0-alpha.3", path = "traits", default-features = false }
ink_prelude = { version = "4.0.0-alpha.3", path = "../prelude/", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "full"] }
derive_more = { version = "0.99", default-features = false, features = ["from", "display"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }
cfg-if = "1.0"
array-init = { version = "2.0", default-features = false }

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
itertools = "0.10"

ink = { path = "../ink" }

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_prelude/std",
    "ink_primitives/std",
    "ink_storage_traits/std",
    "scale/std",
    "scale-info/std",
]
ink-fuzz-tests = ["std"]
