[package]
name = "ink_ir"
documentation = "https://docs.rs/ink_ir/"

version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[lib]
name = "ink_ir"

[dependencies]
quote = "1"
syn = { version = "1.0", features = ["parsing", "full", "visit", "extra-traits"] }
proc-macro2 = "1.0"
itertools = { version = "0.10", default-features = false }
either = { version = "1.5", default-features = false }
blake2 = "0.10"

[features]
default = ["std"]
std = [
    "itertools/use_std",
    "either/use_std",
]
