[package]
name = "ink_macro"
documentation = "https://docs.rs/ink_macro/"

version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[dependencies]
ink_ir = { version = "4.0.0-alpha.3", path = "../ir", default-features = false }
ink_codegen = { version = "4.0.0-alpha.3", path = "../codegen", default-features = false }
ink_primitives = { version = "4.0.0-alpha.3", path = "../../primitives/", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
syn = "1"
synstructure = "0.12.6"
proc-macro2 = "1"
quote = "1"

[dev-dependencies]
ink_env = { path = "../../env" }
ink = { path = ".." }
ink_metadata = { path = "../../metadata" }
ink_prelude = { path = "../../prelude" }
ink_storage = { path = "../../storage" }
scale-info = { version = "2", default-features = false, features = ["derive"] }

[lib]
name = "ink_macro"
proc-macro = true

[features]
default = ["std"]
std = [
    "scale/std",
    "ink_ir/std",
    "ink_primitives/std",
]
