[package]
name = "ink"
documentation = "https://docs.rs/ink"

version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[dependencies]
ink_env = { version = "4.0.0-beta", path = "../env", default-features = false }
ink_storage = { version = "4.0.0-beta", path = "../storage", default-features = false }
ink_primitives = { version = "4.0.0-beta", path = "../primitives", default-features = false }
ink_metadata = { version = "4.0.0-beta", path = "../metadata", default-features = false, optional = true }
ink_prelude = { version = "4.0.0-beta", path = "../prelude", default-features = false }
ink_macro = { version = "4.0.0-beta", path = "macro", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "full"] }
derive_more = { version = "0.99", default-features = false, features = ["from"] }

[dev-dependencies]
ink_ir = { path = "./ir" }
ink_metadata = { path = "../metadata", default-features = false }

trybuild = { version = "1.0.60", features = ["diff"] }
# Required for the doctest of `env_access::EnvAccess::instantiate_contract`
scale-info = { version = "2.3", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_prelude/std",
    "ink_primitives/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_macro/std",
    "scale/std",
]
# Enable contract debug messages via `debug_print!` and `debug_println!`.
ink-debug = [
    "ink_env/ink-debug",
]
show-codegen-docs = []
