[package]
name = "ink_traits"
version = "4.0.0-alpha.3"
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink"
homepage = "https://www.parity.io/"
description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_primitives = { version = "4.0.0-alpha.3", path = "../../primitives", default-features = false }
ink_macro = { version = "4.0.0-alpha.3", path = "../macro", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "full"] }
num-traits = { version = "0.2", default-features = false, features = ["i128"] }

[features]
default = ["std"]
std = [
    "scale/std",
    "num-traits/std",
    "ink_primitives/std"
]
