[package]
name = "ink_e2e_macro"
documentation = "https://docs.rs/ink_e2e_macro"
publish = false

version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true

[lib]
name = "ink_e2e_macro"
proc-macro = true

[dependencies]
ink_ir = { version = "4.0.0-beta", path = "../../ink/ir" }
contract-build = "2.0.0-beta.1"
derive_more = "0.99.17"
env_logger = "0.10.0"
log = "0.4.17"
serde_json = "1.0.89"
syn = "1"
proc-macro2 = "1"
quote = "1"
